### ISSUE TITLE
socket.io link

### ISSUE THREAD

**Issue by phtphan** [nowelium/socket.io-titanium#1]
Hi Yusuke Hata,

I've tried to use socket.io-titanium today but failed since my Resources/socket.io (https://github.com/LearnBoost/socket.io.git) folder is some how different from the one that you listed in the README.

Also the git link to socket.io from README is also broken.

Please help me take a look,

Thanks,

Phillip Phan

**Comment by phtphan** [comment]
Shoud it refer to this?  https://github.com/LearnBoost/socket.io-client.git

**Comment by nowelium** [comment]
Hi phtphan,

Sorry for the late response.
First, Please forgive thing with unskilled English.(i'm sorry...)

README was outdated. i'm sorry.

https://github.com/LearnBoost/Socket.IO.git (source https://github.com/LearnBoost/Socket.IO), it was deadlinked be just newly released(socket.io-0.7.0) several days ago. 

I made the branch including the code of 0.6.2 at local-code.:
https://github.com/nowelium/socket.io-titanium/tree/socket.io-node-client-0.6.2

please try 'git clone git@github.com:nowelium/socket.io-titanium.git -b socket.io-node-client-0.6.2' and use
i'm writing for corresponding to socket.io-0.7.0 is scheduled to public by the end of several days. 

thanks,
Yusuke Hata

**Comment by phtphan** [comment]
Thanks Yusuke,

I'll try that right away.

I have another question about the Transport: Currently, seem like it is using "xhr-polling" transport. Is it possible to use "websocket" instead?

Thanks,

Phillip Phan

**Comment by kn0ll** [comment]
Just to chime in as I did a bit of looking myself recently... Titanium doesn't support Websockets at the moment as far as I can tell. They do support TCP sockets though, which would be preferable.

The issue there is that the entire backend of Socket.IO (every transport) is set up to run through nodes HTTP server, not it's TCP server... so it would require a bit of manipulation...

**Comment by nowelium** [comment]
hi phtphan,

> "websocket" implementation

not yet now. It is necessary to wait until it comes to be able to use WebSocket by TiMob. 

or Ti.Network.Socket.TCP might be able to implements like ActionScript implementation(https://github.com/LearnBoost/socket.io-client/blob/master/lib/vendor/web-socket-js/flash-src/WebSocket.as)

... but time cannot be taken, it is not to try...
